%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%1.analyzethesignals-STFT
wlen=1024;timestep=512;numfreq=1024;
awin=hamming(wlen);%analysiswindowisaHammingwindow
tf1=tfanalysis(x1,awin,timestep,numfreq);%time-freqdomain
tf2=tfanalysis(x2,awin,timestep,numfreq);%time-freqdomain
tf1(1,:)=[];tf2(1,:)=[];%removedccomponentfrommixtures
%toavoiddividingbyzerofrequencyinthedelayestimation
%calculatepos/negfrequenciesforlateruseindelaycalc
freq=[(1:numfreq/2) ((-numfreq/2)+1:-1)]*(2*pi/(numfreq));
fmat=freq(ones(size(tf1,2),1),:)';
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%2.calculatealphaanddeltaforeacht-fpoint
R21=(tf2+eps)./(tf1+eps);%time-freqratioofthemixtures
%%%2.1HEREWEESTIMATETHERELATIVEATTENUATION(alpha)%%%
a=abs(R21);%relativeattenuationbetweenthetwomixtures
alpha=a-1./a;%’alpha’(symmetricattenuation)
%%%2.2HEREWEESTIMATETHERELATIVEDELAY(delta)%%%%
delta=-imag(log(R21))./fmat;%’delta’relativedelay
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%3.calculateweightedhistogram
p=1;q=0;%powersusedtoweighthistogram
tfweight=(abs(tf1).*abs(tf2)).^p.*abs(fmat).^q;%weights
maxa=0.7;maxd=3.6;%histboundaries
abins=35;dbins=50;%numberofhistbins
%onlyconsidertime-freqpointsyieldingestimatesinbounds
amask=(abs(alpha)<maxa)&(abs(delta)<maxd);
alphavec=alpha(amask);
deltavec=delta(amask);
tfweight=tfweight(amask);
%determinehistogramindices
alphaind=round(1+(abins-1)*(alphavec+maxa)/(2*maxa));
deltaind=round(1+(dbins-1)*(deltavec+maxd)/(2*maxd));
%FULL-SPARSETRICKTOCREATE2DWEIGHTEDHISTOGRAM
A=full(sparse(alphaind,deltaind,tfweight,abins,dbins));
%smooththehistogram-localaverage3-by-3neighboringbins
A=twoDsmooth(A,3);
%plot2-Dhistogram
mesh(linspace(-maxd,maxd,dbins),linspace(-maxa,maxa,abins),A);